# Generated by Django 6.1 on 2026-08-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fooditem_image_alter_restaurant_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': 'Food categories'},
        ),
        migrations.AlterModelOptions(
            name='restaurantcategory',
            options={'verbose_name_plural': 'Restaurant categories'},
        ),
    ]
