# Generated by Django 6.1 on 2026-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_liveitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='live_items/'),
        ),
    ]
