# Generated by Django 6.1 on 2026-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_liveitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.CharField(blank=True, help_text='Comma separated ingredients', max_length=255),
        ),
    ]
