# Generated by Django 6.1 on 2026-09-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payment_options_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('KHQR', 'KHQR'), ('COD', 'Cash on Delivery'), ('WALLET', 'Wallet Account Balance')], default='KHQR', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('ABA', 'ABA KHQR'), ('ACLEDA', 'ACLEDA KHQR'), ('COD', 'Cash on Delivery'), ('WALLET', 'FoodGo Wallet')], default='ABA', max_length=20),
        ),
    ]
