# Generated by Django 6.1 on 2026-09-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_payment_method_alter_payment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste direct web image URL (e.g. Unsplash) or upload file', max_length=500, null=True),
        ),
    ]
