# Generated by Django 6.1 on 2026-09-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fooditem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('BAKONG', 'Bakong KHQR'), ('ABA', 'ABA KHQR'), ('ACLEDA', 'ACLEDA KHQR'), ('COD', 'Cash on Delivery'), ('WALLET', 'FoodGo Wallet')], default='ABA', max_length=20),
        ),
    ]
